name: HqngLastLocation
version: '${version}'
main: tech.qhuyy.lastlocation.LastLocation
author: hqng05
website: https://qhuyy.tech
api-version: '1.21'
depend: [Multiverse-Core]
description: Auto-save logout position and teleport back with Multiverse safe teleport.

commands:
  lastlocation:
    description: Teleport to your last saved location
    usage: /<command> [player|reload]
    permission: arclyx0.teleport.self
    aliases: [ll]

permissions:
  hqngll.teleport.self:
    description: Allows teleporting yourself to your last location
    default: true
  hqngll.teleport.others:
    description: Allows teleporting another player to their last location
    default: op
  hqngll.admin:
    description: Admin permission (reload config, includes all other permissions)
    default: op
    children:
      arclyx0.teleport.self: true
      arclyx0.teleport.others: true
